apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: progressive-delivery
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shubhuk7051/progressive-delivery-eks.git
    targetRevision: main
    path: app/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: progressive-delivery
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Service
      name: progressive-delivery-canary
      jsonPointers:
        - /spec/selector
    - group: ""
      kind: Service
      name: progressive-delivery-stable
      jsonPointers:
        - /spec/selector